- https://www.functionalgeekery.com/feed/mp3/
- http://www.magicreadalong.com/episode?format=rss
- https://feeds.soundcloud.com/users/soundcloud:users:24638646/sounds.rss
- http://www.haskellcast.com/feed.xml
- http://feeds.feedburner.com/MostlyErlangPodcast
- http://feeds.feedburner.com/cognicast
- https://feeds.soundcloud.com/users/soundcloud:users:239787249/sounds.rss
- http://feeds.soundcloud.com/users/soundcloud:users:220484243/sounds.rss
- http://fsharpshow.com/index.xml
- http://typetheorypodcast.com/feed/podcast/
- http://feeds.feedburner.com/MostlyLazy
- https://cast.rocks/hosting/6039/feeds/8YSE5.xml
- https://jstoelm.libsyn.com/rss
- https://feeds.soundcloud.com/users/soundcloud:users:334579745/sounds.rss
- https://wtfsharp.net/rss
- https://rss.simplecast.com/podcasts/4151/rss
- https://feeds.therepl.net/therepl
- https://clojuredesign.club/index.xml
- https://scala.love/feed/sonus-feed
- https://feeds.feedwrench.com/elixirmix.rss
- https://feeds.fireside.fm/elixiroutlaws/rss
- https://corecursive.libsyn.com/feed
- https://feeds.soundcloud.com/users/soundcloud:users:627190089/sounds.rss
- https://haskellweekly.news/podcast/feed.rss
- https://newrustacean.com/feed.xml
