- https://www.functionalgeekery.com/feed/mp3/
- http://www.magicreadalong.com/episode?format=rss
- https://feeds.soundcloud.com/users/soundcloud:users:24638646/sounds.rss
- http://www.haskellcast.com/feed.xml
- http://thescalawags.libsyn.com/rss
- http://feeds.feedburner.com/MostlyErlangPodcast
- http://feeds.feedburner.com/cognicast
- https://feeds.soundcloud.com/users/soundcloud:users:239787249/sounds.rss
- http://feeds.soundcloud.com/users/soundcloud:users:220484243/sounds.rss
- http://fsharpshow.com/index.xml
- http://typetheorypodcast.com/feed/podcast/
- http://feeds.feedburner.com/MostlyLazy
